services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: todo
    volumes:
      - todo_pgdata:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      DBUSER: postgres
      DBPASSWORD: example
      DBNAME: todo
      DBHOST: db
      DBPORT: "5432"
    ports:
      - "3001:3001"
    labels:
      com.datadoghq.ad.logs: '[{"source":"nodejs","service":"grabsentinel-backend"}]'

volumes:
  todo_pgdata:
