CREATE TABLE IF NOT EXISTS todo_items (
  id SERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  completed BOOLEAN DEFAULT FALSE,
  status TEXT NOT NULL DEFAULT 'todo',
  created_at TIMESTAMP DEFAULT now()
);
